### ISSUE TITLE
Design Review: Login.gov SSO integration on Desktop

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#540] opened 2022-05-03 21:13 UTC
The bulk of the copy, design, and code changes have been deployed to https://dev-benefits.calitp.org

@Indiajar @srhhnry can you please provide _Design_ feedback or sign-off on the screens in **Desktop only**.

Note this is not intended to be a _functional_ review, we are just looking for feedback/sign-off on the look and feel.

## Resources

* [Figma mocks](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Login.gov)?node-id=2133%3A10111)
* [Benefits test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit)

## Pages to review

Listing each page individually with the URL, but note that most of these URLs require progressing through the app and cannot be navigated to directly.

* [ ] `Index`: https://dev-benefits.calitp.org
  > Indirect entry/provider choice: Spacing on this page looked a little scrunched. The H2 copy and MST button should be dropped further down the page to about the middle.

![Image](https://user-images.githubusercontent.com/3673236/167700298-6fc83f89-12b2-44fe-b73d-58290fa3cb7d.png)

* [ ] `Agency index`: https://dev-benefits.calitp.org/mst
  > Direct Entry/MST page: The H2 copy over the call-to-action button should be centered over the button. It appears to be left justified at the moment

![Image](https://user-images.githubusercontent.com/3673236/167700345-cab8c45a-f69f-46b2-8203-db5986d93ac0.png)

* [ ] `Eligibility: Getting Started`: https://dev-benefits.calitp.org/eligibility/start
  > Eligibility/Get started page: Currently requires a slight scroll to see the entire page—the whole page should be visible without scrolling. There also appears to be centering of the icons over the text copy, but the text boxes/divs are different sizes for each of the three steps, or at least at different break points. So for example, Step 1 might have 7 words across whereas Step 2 has 5 words across. Overall, what we’re seeing on that page is that it looked unbalanced or has strange centering at different screen sizes. Happy to jump on a call/screen share to talk through this

![Image](https://user-images.githubusercontent.com/3673236/167700389-6ba218d8-4313-4007-8dbc-212feaf35a31.png)

* [x] `Eligibility: Confirm`: https://dev-benefits.calitp.org/eligibility/confirm (must pass Login.gov, use a test account)
  > Confirm Eligibility page: Looks good, no notes

![Image](https://user-images.githubusercontent.com/3673236/167700691-e02cde0f-7766-49ba-b2f4-40aab0baf2e9.png)

* [x] `Eligibility: Confirm (not eligible)`: https://dev-benefits.calitp.org/eligibility/confirm (fail Eligibility Verification, use an ineligible user from test data)

![Image](https://user-images.githubusercontent.com/3673236/167700653-1fc05370-2664-4f91-8db0-5d6e7c9108a7.png)

* [ ] `Enrollment: Index`: https://dev-benefits.calitp.org/enrollment/ (pass Eligibility Verification, use an eligible user from test data)
  > Eligibility Success page: At different break points the body copy gets pushed down closer to the call-to-action button than we would like. I think what’s happening is that the icon is set at a certain height on the page and everything follows from there. On pages without an icon there’s more fluidity (I think). It would be preferable if the icons were giving the same treatment as H1 headlines, and moved farther up on the page to allow for more white space between copy and call-to-action buttons. Again, happy to walk through this on a screen share.

![Image](https://user-images.githubusercontent.com/3673236/167700800-5c9485fc-50a5-49e7-850d-acfe974d1d4d.png)

* [ ] `Enrollment: Success`: https://dev-benefits.calitp.org/enrollment/success (must pass Enrollment, use valid payment details from test data)
  > Success Page: Same issue with the icon feeling too far down on the page, squishing the body copy. We’re also considering removing the line, “You were not charged anything today.” Based on user feedback and also logical consistency from the headline.

![Image](https://user-images.githubusercontent.com/3673236/167700916-e9352f05-6d30-4ee0-90c0-fd2b8f302f56.png)

* [ ] #565
  > Logged out page: We prefer the Alt page in the Figma boards (full-screen with no image) but this is low-priority and the page looks fine as is.

![Image](https://user-images.githubusercontent.com/3673236/167700965-50b45953-f9bc-4718-8972-90f550d64879.png)

* [x] `Help`: https://dev-benefits.calitp.org/help
* [ ] #567

**Comment by angela-tran** [comment] 2022-05-09 18:52
**Initial design review** from @srhhnry and @Indiajar as communicated in [Sarah's Slack thread](https://cal-itp.slack.com/archives/C037Y3UE71P/p1651687139200169):

> I’ll cover this page by page, by the overarching summary is that things are looking pretty good! The main problems we saw were with text spacing at different break points and a few items being centered or justified left incorrectly. Lastly, the Get Started page had some centering issues, which we think are based on the size of the divs for copy.

> Indirect entry/provider choice: Spacing on this page looked a little scrunched. The H2 copy and MST button should be dropped further down the page to about the middle.
> 
> Direct Entry/MST page: The H2 copy over the call-to-action button should be centered over the button. It appears to be left justified at the moment
> 
> Eligibility/Get started page: Currently requires a slight scroll to see the entire page—the whole page should be visible without scrolling. There also appears to be centering of the icons over the text copy, but the text boxes/divs are different sizes for each of the three steps, or at least at different break points. So for example, Step 1 might have 7 words across whereas Step 2 has 5 words across. Overall, what we’re seeing on that page is that it looked unbalanced or has strange centering at different screen sizes. Happy to jump on a call/screen share to talk through this
> 
> Confirm Eligibility page: Looks good, no notes
> 
> Eligibility Success page: At different break points the body copy gets pushed down closer to the call-to-action button than we would like. I think what’s happening is that the icon is set at a certain height on the page and everything follows from there. On pages without an icon there’s more fluidity (I think). It would be preferable if the icons were giving the same treatment as H1 headlines, and moved farther up on the page to allow for more white space between copy and call-to-action buttons. Again, happy to walk through this on a screen share.
> 
> Success Page: Same issue with the icon feeling too far down on the page, squishing the body copy. We’re also considering removing the line, “You were not charged anything today.” Based on user feedback and also logical consistency from the headline.
> 
> Logged out page: We prefer the Alt page in the Figma boards (full-screen with no image) but this is low-priority and the page looks fine as is.
> 
> Service is down page: Drop the Return Home button further down the page and center the headline. We don’t have a comp for this, but can make one if that’s easier.

**Comment by afeld** [comment] 2022-05-09 21:00
@machikoyasuda to convert these to smaller standalone issues after going through to confirm each, and also working with Design team to identify root causes.

**Comment by machikoyasuda** [comment] 2022-05-10 22:13
Went over all these tickets in a meeting.

Closing this issue and creating detailed tickets for next steps.

**Closed by machikoyasuda** 2022-05-10 22:13 UTC
Labels: design
