### ISSUE TITLE
Cypress: refactor UI tests and re-enable CI runs

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#724] opened 2022-06-22 21:26 UTC
In #721 we turned off Cypress test runs in CI. This is the follow-up task to address more of the underlying issues, and to get the tests back up and running in CI again.

## Acceptance Criteria

- [x] Cypress tests are running (and passing) in GitHub Actions
- [ ] *more to come soon*

## Related

* #681 
* #813

**Comment by machikoyasuda** [comment] 2022-07-11 20:06
Decision as of July 2022: Will revisit this ticket and Cypress usage overall when we have new features to build. For the time being, the IAL2 Login.gov flow is not conducive to Cypress testing. Instead, we will continue to increase test coverage with Pytest (see #680 etc.)

**Comment by afeld** [comment] 2023-02-06 23:45
Is this a duplicate of https://github.com/cal-itp/benefits/issues/340?

**Comment by machikoyasuda** [comment] 2023-02-07 20:44
@afeld These two tickets are slightly different:

This ticket refers to turning off Cypress UI tests (all the specs in this `/ui/` directory https://github.com/cal-itp/benefits/tree/dev/tests/cypress/specs/ui) and #340 refers to the specs in the `/feature/` directory. The UI tests are testing to see if certain specific UI elements (buttons, text fields, etc.) appear on the correct pages. The Feature tests (like this one https://github.com/cal-itp/benefits/blob/dev/tests/cypress/specs/feature/eligibility.cy.js) actually go through several pages to complete a whole flow.

**Comment by afeld** [comment] 2023-02-16 03:33
It does seem some of the UI tests were still useful, so keeping this issue as-is. Split out an issue around accessibility: https://github.com/cal-itp/benefits/issues/1278

**Closed** 2023-02-17 00:20 UTC
Labels: tests, front-end, actions
